---
galaxy_info:
  role_name: rke2
  author: Almas
  description: Production-ready RKE2 installation
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - rke2
    - kubernetes
    - rancher
    - container

dependencies: []
