---
- name: Install | Ensure auditd packages are present
  ansible.builtin.package:
    name: "{{ auditd_packages_map.get(ansible_os_family) }}"
    state: present
  become: true

- name: Install | Ensure auditd service is enabled
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    daemon_reload: true
  become: true
